# Defining Variables

In [1]:
height = 1.70

In [2]:
weight = 65

In [3]:
bmi = weight / height ** 2

In [4]:
bmi

22.49134948096886

Command to know variable type

In [5]:
type(bmi)

float

Adding variables which are defined as strings

In [6]:
x = 'ab'
y = 'bc'

In [7]:
x+y

'abbc'

Creating a list, list index starts from 0,1, 2....n-1

In [8]:
family = ["I", 1.73, "mom", 1.68, "dad", 1.75, "brother", 1.89, "sister", 1.66]

getting a single element from list by mentioning index.

In [9]:
family[2]

'mom'

Selecting elements from a range of list. In indexing starting element is included whereas ending element is not included.

In [10]:
family[2:5]

['mom', 1.68, 'dad']

replacing elements in a list

In [11]:
family[2] = 'vrc'

In [12]:
family

['I', 1.73, 'vrc', 1.68, 'dad', 1.75, 'brother', 1.89, 'sister', 1.66]

# creating duplicate of the family list

In [13]:
duplicatefam = family

In [14]:
duplicatefam

['I', 1.73, 'vrc', 1.68, 'dad', 1.75, 'brother', 1.89, 'sister', 1.66]

changing one of the element in the duplicate list

In [15]:
duplicatefam[1] = 1.52

In [16]:
duplicatefam

['I', 1.52, 'vrc', 1.68, 'dad', 1.75, 'brother', 1.89, 'sister', 1.66]

In [17]:
family

['I', 1.52, 'vrc', 1.68, 'dad', 1.75, 'brother', 1.89, 'sister', 1.66]

here we have changed duplicate, it also changed orginal parent elements in list.

# copy family list

copying the orginal family list 

In [18]:
family

['I', 1.52, 'vrc', 1.68, 'dad', 1.75, 'brother', 1.89, 'sister', 1.66]

In [19]:
copyfam = family[:]

In [20]:
copyfam[6] = 'geek'

In [21]:
copyfam

['I', 1.52, 'vrc', 1.68, 'dad', 1.75, 'geek', 1.89, 'sister', 1.66]

In [22]:
family

['I', 1.52, 'vrc', 1.68, 'dad', 1.75, 'brother', 1.89, 'sister', 1.66]

heights of family as a list

In [23]:
heights = [1.75, 1.5, 1.7, 1.8, 1.66]

In [24]:
shortest= min(heights)

In [25]:
shortest

1.5

In [26]:
longest= max(heights)

In [27]:
longest

1.8

# Python Libraries

**Numpy**: NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

**Pandas**: Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures, data manipulation data analysis tools for the Python programming language.

**Scikit-Learn**: scikit-learn is a high-level framework designed for supervised and unsupervised machine learning algorithms. Being one of the components of the Python scientific ecosystem, it's built on top of NumPy and SciPy libraries, each responsible for lower-level data science tasks.

**Matplotlib**: Matplotlib is a plotting library for the Python programming language and its numerical mathematics extension NumPy.

**Seaborn**: Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics.

# Calculations using Numpy

In [28]:
#importing numpy python library
import numpy as np

In [29]:
np_heights = np.array(heights)

In [30]:
np_heights

array([1.75, 1.5 , 1.7 , 1.8 , 1.66])

In [43]:
weights = [65, 55, 95, 72, 65]

In [44]:
np_weights =  np.array(weights)

In [45]:
np_weights

array([65, 55, 95, 72, 65])

In [46]:
bmi = np_weights/np_heights ** 2

In [47]:
bmi

array([21.2244898 , 24.44444444, 32.87197232, 22.22222222, 23.58832922])

Adding lists and arrays

In [54]:
addinglists = heights + weights

In [55]:
addinglists 

[1.75, 1.5, 1.7, 1.8, 1.66, 65, 55, 95, 72, 65]

In [56]:
addingarrays = np_heights + np_weights

In [57]:
addingarrays

array([66.75, 56.5 , 96.7 , 73.8 , 66.66])

In [ ]:
That is the difference betw